""" This module defines a dictionary of legal terms found in company's name."""

legal_terms_dict = {
    "registered limited liability limited partnership": [
        "registered limited liability ltd. partnership",
        "registered l.l.l.p.",
        "registered l.l.l.p",
        "registered lllp",
        "registered lllp.",
        "r.l.l.l.p.",
        "r.l.l.l.p",
        "rlllp.",
        "rlllp"
    ],
    "registered limited liability partnership": [
        "registered limited liability partnership",
        "registered l.l.p.",
        "registered l.l.p",
        "registered llp.",
        "registered llp",
        " r.l.l.p.",
        " r.l.l.p",
        "rllp.",
        "rllp"
    ],
    "limited liability limited partnership": [
        "professional limited liability limited partnership",
        "limited liability limited partnership",
        "limited l.l.p.",
        "limited l.l.p",
        "limited llp.",
        "limited llp",
        "lllp",
        "lllp.",
        "l.l.l.p.",
        "l.l.l.p"
    ],
    "limited liability partnership": [
        "professional limited liabity partnership",
        "limited liability partnership",
        "limited l.p.",
        "limited l.p",
        "limited lp.",
        "limited lp",
        "pllp",
        "p.l.l.p",
        "p.l.l.p."
        "l.l.p.",
        "l.l.p",
        "llp",
        "llp."
    ],
    "limited liability company": [
        "professional series limited liability company",
        "professional limited liability company",
        "low-profit limited liability company",
        "farm/ranch limited laibility company",
        "farm/ranch limited liability company",
        "series limited liability company",
        "master limited liability company",
        "limited liabilty company",
        "limited liability company",
        "limited liability co.",
        "limited liability co",
        "ltd. liability company",
        "ltd. liability co.",
        "ltd. liability co",
        "ltd liability co.",
        "ltd liability co",
        "l3c low llc",
        "benefit llc",
        "low llc",
        "l.l.c.",
        "l.l.c",
        "llc",
        "llc.",
        "l3c",
        "l3c.",
        "l.3.c.",
        "p.l.l.c.",
        "pllc",
        "pllc.",
        "plc",
        "plc."
    ],
    "limited partnership": [
        "limited partnership",
        "limted partnership",
        "ltd. partnership.",
        "ltd. partnership",
        "ltd partnership",
        "lp.",
        "lp",
        "l.p.",
        "l.p"
    ],
    "limited": [
        "ltd",
        "ltd.",
        "lt."
    ],
    "incorporated": [
        "inc",
        "inc.",
        "incorp",
        "incorp."
    ],
    "district": [
        "dist",
        "dist."
    ],
    "commission": [
        "comm",
        "comm."
    ],
    "corporation": [
        "sustainable business corporation",
        "religious society or religious corporation",
        "ecclesiastical corporation",
        "religious society",
        "religious corporation",
        "religious corporations",
        "corporation religious",
        "county agricultural fair",
        "farm/ranch corporation",
        "business development corporation",
        "general business corporation",
        "congressional chartered corporation",
        "professional service corporation",
        "professional benefit corporation",
        "corp professional corporation",
        "corporation professional corporation",
        "professional close corporation",
        "benefit professional corporation",
        "professional corporation",
        "corporation professional",
        "professional firms",
        "professional firm",
        "community development corporation",
        "corporation mutual benefit",
        "mutual benefit corporation",
        "nebraska benefit corporation",
        "corporation general stock",
        "corporation nonstock",
        "nonstock corporation",
        "non stock corporation",
        "stock corporation",
        "non taxable corporation",
        "corporation benefit",
        "business corporation",
        "development corporation",
        "public benefit corporation",
        "a benefit corporation",
        "benefit corporation",
        "captive insurance company",
        "insurance company",
        "insurance corporation",
        "insurance corporations",
        "financial corporation",
        "financial corporations",
        "investment company",
        "corporation sole",
        "limited corp",
        "company, co.",
        "statutory close corporation",
        "close corporation",
        "corporation close",
        "chartered",
        "prof. corp.",
        "prof corp.",
        "prof corp",
        "company",
        "corporation",
        "corp.",
        "corp",
        "co.",
        "co",
        "p.a.",
        "pa.",
        "p.c.",
        "p.c",
        "pc.",
        "psc",
        "bc.",
        "b.c.",
        "chtd",
        "chtd.",
        "cdc",
        "cdc.",
        "c.d.c."
    ],
    "trust": [
        "voluntary association and business trusts",
        "real estate investment trust",
        "family trust company",
        "real estate investment trusts",
        "common law trust",
        "statutory trust",
        "business trust",
        "business trust",
        "investment trust",
        "community trust",
        "trust company",
        "trust",
        "reit",
        "reit.",
        "r.e.i.t.",
        "b.t.",
        "bt."
    ],
    "general partnership": [
        "gp.",
        "g.p."
    ],
    "commercial registered agent": [
        "commercial registered agent",
        "c.r.a.",
        "cra",
        "cra."
    ],
    "credit union": [
        "corporate credit union",
        "credit union"
    ],
    "authority": [
        "hospital authority",
        "transportation authority",
        "authority",
        "auth",
        "auth."
    ],
    "foundation": [
        "statutory foundation",
        "foundation",
        "found",
        "found.",
        "sf.",
        "s.f."
    ],
    "cooperative": [
        "electric generation and transmission cooperative corporation",
        "electric cooperative membership corporation",
        "electric membership cooperative",
        "electric cooperative corporation",
        "electric cooperative corporations",
        "uniform limited cooperative association",
        "limited cooperative association",
        "general cooperative association",
        "cooperative marketing association",
        "cooperative grazing associations",
        "agricultural cooperative",
        "housing cooperative corporation",
        "employee cooperative corporation",
        "limited cooperative",
        "mutual aid cooperative",
        "cooperative corporation",
        "cooperative association",
        "workers cooperative",
        "cooperative",
        "co-operatives",
        "co-operative",
        "co operative",
        "ltd. co-op",
        "ltd. coop",
        "ltd. co-op.",
        "ltd. coop.",
        "ltd co-op",
        "ltd coop",
        "emc.",
        "co-op",
        "coop",
        "coop."
        "l.c.a.",
        "lca",
        "lca.",
        "c.a.",
        "c.a"
    ],
    "association": [
        "common interest development association",
        "builiding and loan association",
        "agricultural marketing association",
        "agricultural association",
        "rural cooperative association",
        "limited partnership association",
        "savings & loan association",
        "savings and loan association",
        "unincorporated association",
        "professional association",
        "cemetery association",
        "cemetery associations",
        "mutual burial association",
        "mutual association",
        "voluntary association",
        "s&l",
        "assoc.",
        "assoc",
        "assn.",
        "assn"
    ]
}

cleaning_rules_dict = {
    'remove_email': ['', '\S*@\S*\s?'],
    'remove_url': ['', 'https*\S+'],
    'remove_www_address': ['', 'https?://[.\w]{3,}|www.[.\w]{3,}'],
    'enforce_single_space_between_words': [' ', '\s+'],
    'treat_AND': [' and ', '(&)'],
    'replace_hyphen_underscore_by_space': [' ', '(-|_)'],
    'remove_all_punctuation': ['', '([^\w\s])'],
    'remove_mentions': ['', '@\S+'],
    'remove_hashtags': ['', '#\S+'],
    'remove_numbers': ['', '\w*\d+\w*'],
    'remove_single_quote_next_character': ['', '\'\w+'],
    'remove_words_in_parentheses': ['', '\([^()]*\)']
}

default_company_cleaning_rules = ['remove_words_in_parentheses',
                                  'replace_hyphen_underscore_by_space',
                                  'treat_AND',
                                  'remove_all_punctuation',
                                  'enforce_single_space_between_words'
                                  ]